#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';
require __DIR__.'/src/helpers.php';

use Dotenv\Dotenv;
use SteamWebApiGenerator\Application;

$configFile = '.env';

if (is_readable(rtrim(__DIR__, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR.$configFile)) {
    $dotenv = new Dotenv(__DIR__, $configFile);
    $dotenv->load();
}

$application = new Application();
$application->run();
